version: '2'

services:

  base:
    build: ./images/docker-debian-oracle-java8
    image: docker-debian-oracle-java8
    
  tomcat8:
    depends_on:
      - base
    build: ./images/docker-debian-oracle-java8-tomcat8
    container_name: tomcat8
    ports:
      - "8080:8080"
    #  - "8009:8009"
    volumes:
      - "/opt/tomcat/webapps/:/opt/tomcat/webapps/"
    command: /opt/tomcat/bin/catalina.sh run

